### ISSUE TITLE
error while running the application

### ISSUE THREAD

**Issue by tkumark** [Azure-Samples/active-directory-dotnet-daemon-v2#17]
I get the following error when running 

Could not find a part of the path 'D:\Temp\active-directory-v2-master\UserSync\bin\roslyn\csc.exe'.

**Comment by kalyankrishna1** [comment]
Follow the steps provided here ([SO Post](https://stackoverflow.com/questions/32780315/could-not-find-a-part-of-the-path-bin-roslyn-csc-exe), one of them should work

**Comment by jmprieur** [comment]
@kalyankrishna1 : can't we upgrade the sample to use the following NuGet packages with the latest compatible (read same major number) version?
`Microsoft.Net.Compilers` and  `Microsoft.CodeDom.Providers.DotNetCompilerPlatform`

**Comment by kalyankrishna1** [comment]
this should have been fixed by now
